// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfeu-GrcA1kNpiVu5jlUrPvw8b0DKyvGg',
    appId: '1:313084539240:web:51fa923ffd62910865a6dd',
    messagingSenderId: '313084539240',
    projectId: 'dictionary-3a6a4',
    authDomain: 'dictionary-3a6a4.firebaseapp.com',
    storageBucket: 'dictionary-3a6a4.appspot.com',
    measurementId: 'G-5P4R3FVT2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuHs0vekw1WMISj45u0ODHBnQkBeKrnTc',
    appId: '1:313084539240:android:eb0621d28948d96965a6dd',
    messagingSenderId: '313084539240',
    projectId: 'dictionary-3a6a4',
    storageBucket: 'dictionary-3a6a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgzvrHK4NTyqEqs27sG4XFK-AUPvRUPfo',
    appId: '1:313084539240:ios:975352f86f2e116f65a6dd',
    messagingSenderId: '313084539240',
    projectId: 'dictionary-3a6a4',
    storageBucket: 'dictionary-3a6a4.appspot.com',
    iosBundleId: 'com.example.personalDictionary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgzvrHK4NTyqEqs27sG4XFK-AUPvRUPfo',
    appId: '1:313084539240:ios:ae72b77d2220004f65a6dd',
    messagingSenderId: '313084539240',
    projectId: 'dictionary-3a6a4',
    storageBucket: 'dictionary-3a6a4.appspot.com',
    iosBundleId: 'com.example.personalDictionary.RunnerTests',
  );
}
